version: '3.8'

services:
  app:
    build: .
    image: my-custom-node-python-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && node index.js"
    environment:
      - NODE_ENV=online
    networks:
      - my-net
    restart: always

  my-redis:
    image: redis:latest
    volumes:
      - redis-data:/data
    networks:
      - my-net
    restart: always

volumes:
  redis-data:

networks:
  my-net:
    driver: bridge