version: '3.8'

services:
  app:
    image: node:22.10.0
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && node index.js"
    environment:
      - NODE_ENV=development